pca9685_interface:
  ros__parameters:
    channel_mapping:
      # channel: integer 0-15
      # type: 0 = servo, 1 = continuous servo, 2 = generic PWM
      # actuation range, pulse_width_range are only valid for servo types

      # PWM settings from https://www.gobilda.com/2000-series-dual-mode-servo-25-2-torque/
      back_right_servo:
        channel: 0
        type: 0
        actuation_range: 300 # degree
        pulse_width_range: [500, 2500] # [microsec]

      front_right_servo:
        channel: 1
        type: 0
        actuation_range: 300
        pulse_width_range: [500, 2500]

      front_left_servo:
        channel: 2
        type: 0
        actuation_range: 300
        pulse_width_range: [500, 2500]

      back_left_servo:
        channel: 3
        type: 0
        actuation_range: 300
        pulse_width_range: [500, 2500]

      status_light:
        channel: 7
        type: 0
        actuation_range: 100
        pulse_width_range: [500, 2500]

      chassis_fan:
        channel: 4
        type: 2

      pan_motor:
        channel: 6
        type: 0
        actuation_range: 300
        # center: 210
        pulse_width_range: [500, 2500]

      tilt_motor:
        channel: 8
        type: 0
        actuation_range: 120
        # center: 130
        pulse_width_range: [500, 2500]